server:
  port: 8070
  
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/employees?useSSL=false
    username: root
    password: ganesh2689
  jpa:
    generate-ddl: true
    show-sql: true
    
eureka:  client:    service-url:      defaultZone: http://localhost:8092/eureka
        instance:    instance-id: 1
    